# Generated by Django 5.2.7 on 2025-10-11 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PisteCyclable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('longueur', models.FloatField(blank=True, null=True)),
                ('geometry', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
