# Generated by Django 5.2.7 on 2025-10-11 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermisAnimal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('permis_numero', models.CharField(max_length=100, unique=True)),
                ('permis_date_de_debut', models.DateField(blank=True, null=True)),
                ('permis_date_de_fin', models.DateField(blank=True, null=True)),
                ('gardien_territoire_ex_villes', models.CharField(blank=True, max_length=255, null=True)),
                ('animal_type_de_permis', models.CharField(blank=True, max_length=100, null=True)),
                ('animal_nom', models.CharField(blank=True, max_length=255, null=True)),
                ('animal_categorie_race_primaire_de_chiens', models.CharField(blank=True, max_length=100, null=True)),
                ('animal_race_primaire_des_chiens', models.CharField(blank=True, max_length=100, null=True)),
                ('animal_race_croise_des_chiens', models.CharField(blank=True, max_length=100, null=True)),
                ('animal_sexe', models.CharField(blank=True, max_length=20, null=True)),
                ('animal_couleur', models.CharField(blank=True, max_length=100, null=True)),
                ('animal_date_de_naissance', models.DateField(blank=True, null=True)),
                ('animal_vaccination', models.BooleanField(default=False)),
                ('animal_sterilisation', models.BooleanField(default=False)),
                ('animal_poids_kg', models.FloatField(blank=True, null=True)),
                ('animal_micropuce', models.BooleanField(default=False)),
                ('animal_potentiellement_dangereux', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='PisteCyclable',
        ),
    ]
