# Generated by Django 5.2.7 on 2025-10-11 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_permisanimal_delete_pistecyclable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='permisanimal',
            old_name='animal_categorie_race_primaire_de_chiens',
            new_name='animal_categorie',
        ),
        migrations.RenameField(
            model_name='permisanimal',
            old_name='animal_date_de_naissance',
            new_name='animal_date_naissance',
        ),
        migrations.RenameField(
            model_name='permisanimal',
            old_name='animal_potentiellement_dangereux',
            new_name='animal_pot_dangereux',
        ),
        migrations.RenameField(
            model_name='permisanimal',
            old_name='animal_race_croise_des_chiens',
            new_name='animal_race_croise',
        ),
        migrations.RenameField(
            model_name='permisanimal',
            old_name='animal_race_primaire_des_chiens',
            new_name='animal_race_primaire',
        ),
        migrations.RenameField(
            model_name='permisanimal',
            old_name='animal_type_de_permis',
            new_name='animal_type_permis',
        ),
        migrations.RenameField(
            model_name='permisanimal',
            old_name='gardien_territoire_ex_villes',
            new_name='gardien_territoire',
        ),
        migrations.RenameField(
            model_name='permisanimal',
            old_name='permis_date_de_debut',
            new_name='permis_date_debut',
        ),
        migrations.RenameField(
            model_name='permisanimal',
            old_name='permis_date_de_fin',
            new_name='permis_date_fin',
        ),
        migrations.AlterField(
            model_name='permisanimal',
            name='animal_nom',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='permisanimal',
            name='animal_poids_kg',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='permisanimal',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='permisanimal',
            name='permis_numero',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
