# Generated by Django 5.2.7 on 2025-10-11 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_rename_animal_categorie_race_primaire_de_chiens_permisanimal_animal_categorie_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermisConstruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_permis', models.CharField(max_length=50, unique=True)),
                ('type_permis', models.CharField(blank=True, max_length=10, null=True)),
                ('type_permis_descr', models.CharField(blank=True, max_length=255, null=True)),
                ('categorie_batiment', models.CharField(blank=True, max_length=255, null=True)),
                ('type_batiment', models.CharField(blank=True, max_length=255, null=True)),
                ('date_emission', models.DateField(blank=True, null=True)),
                ('structure', models.CharField(blank=True, max_length=100, null=True)),
                ('cout_permis', models.FloatField(blank=True, null=True)),
                ('nombre_etages', models.IntegerField(blank=True, null=True)),
                ('nombre_logements', models.IntegerField(blank=True, null=True)),
                ('sup_ca', models.FloatField(blank=True, null=True)),
                ('lots', models.CharField(blank=True, max_length=100, null=True)),
                ('entrepreneur', models.CharField(blank=True, max_length=255, null=True)),
                ('adresse', models.CharField(blank=True, max_length=255, null=True)),
                ('exville_code', models.CharField(blank=True, max_length=10, null=True)),
                ('exville_descr', models.CharField(blank=True, max_length=100, null=True)),
                ('occupation_debut', models.DateField(blank=True, null=True)),
                ('occupation_fin', models.DateField(blank=True, null=True)),
                ('adresse_details', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
