# Generated by Django 5.2.7 on 2025-10-11 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_permisconstruction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permisconstruction',
            name='lots',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
