# Generated by Django 5.2.7 on 2025-10-20 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_alter_permisconstruction_lots'),
    ]

    operations = [
        migrations.CreateModel(
            name='BonTravailAqueduc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('probleme', models.CharField(blank=True, max_length=100, null=True)),
                ('date_realisee', models.DateField(blank=True, null=True)),
                ('secteur', models.CharField(blank=True, max_length=20, null=True)),
                ('district', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
