# Generated by Django 5.2.7 on 2025-10-20 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_bontravailaqueduc'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistreGES',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_sago', models.CharField(blank=True, max_length=100, null=True)),
                ('annee', models.IntegerField(blank=True, null=True)),
                ('entreprise', models.CharField(blank=True, max_length=255, null=True)),
                ('etablissement', models.CharField(blank=True, max_length=255, null=True)),
                ('scian', models.CharField(blank=True, max_length=255, null=True)),
                ('adresse', models.TextField(blank=True, null=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('mun', models.CharField(blank=True, max_length=100, null=True)),
                ('em_tot', models.FloatField(blank=True, null=True)),
                ('em_bio_comb', models.FloatField(blank=True, null=True)),
                ('em_bio_aut', models.FloatField(blank=True, null=True)),
                ('em_exc_bio', models.FloatField(blank=True, null=True)),
                ('co2_t', models.FloatField(blank=True, null=True)),
                ('ch4_t', models.FloatField(blank=True, null=True)),
                ('n2o_t', models.FloatField(blank=True, null=True)),
                ('hfc_32_t', models.FloatField(blank=True, null=True)),
                ('hfc_125_t', models.FloatField(blank=True, null=True)),
                ('hfc_134a_t', models.FloatField(blank=True, null=True)),
                ('hfc_143a_t', models.FloatField(blank=True, null=True)),
                ('hfc_227ea_t', models.FloatField(blank=True, null=True)),
                ('hfc_245fa_t', models.FloatField(blank=True, null=True)),
                ('hfc_365mfc_t', models.FloatField(blank=True, null=True)),
                ('sf6_t', models.FloatField(blank=True, null=True)),
                ('cf4_t', models.FloatField(blank=True, null=True)),
                ('c2f6_t', models.FloatField(blank=True, null=True)),
                ('c_c4f8_t', models.FloatField(blank=True, null=True)),
                ('hfc_23_t', models.FloatField(blank=True, null=True)),
                ('hfc_43_10mee_t', models.FloatField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('coord_x', models.FloatField(blank=True, null=True)),
                ('coord_y', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
